nameOverride: ''
fullnameOverride: ''
plugin:
  enabled: true
  versionOverride: ''
  endpoint: >-
    https://raw.githubusercontent.com/alessandro-festa/suse-ai-up-ui/dev/extensions/suse-ai-universal-proxy/0.1.2
  compressedEndpoint: >-
    https://raw.githubusercontent.com/alessandro-festa/suse-ai-up-ui/dev/extensions/suse-ai-universal-proxy/0.1.2.tgz
  noCache: false
  noAuth: false
  metadata: {}
